spring:  cloud:    config:      server:        git:          uri: https://github.com/xxce10xx/cursoExpert          repos:            developper:              pattern:                - '*/dev'              clone-on-start: true              uri: https://github.com/xxce10xx/pruebacjava              
#HTTP Server
server:  port: 4444
  