#HTTP Server
server:
  port: 1111

#Discovery Server Access
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    status-page-url-path: /infoCatalogo
    health-check-url-path: /healthCatalogo
    metadata-map:
       app-owner: cedser
       description: test application for the expert course

security:  oauth2:    resource:      user-info-uri: http://localhost:7777/user