management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream, info, health
        
# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

# HTTP Server
server:
  port: 3333 # HTTP (Tomcat) port
  
security:  oauth2:    resource:      user-info-uri: http://localhost:7777/user 
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/carritomicro?useSSL=false
    username: root
    password: diosteama-9
  jpa:
    generate-ddl: true
    
